### ISSUE TITLE
Set Organisation Preferences ( Step 1of 3 ) screen : UI

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#104]
Expected:

1. Back arrow
2. Main icon
3. Placement of skip button should shift towards left
4. There should be more space maintained as depicted by the vertical red line. See below

![image](https://user-images.githubusercontent.com/55691499/74823678-1938ad80-532d-11ea-8021-51a82c37cacf.png)

**Comment by 27amaldev09** [comment]
The back arrow doesn't seem to be proper for this screen

**Comment by HazelColaco19** [comment]
The " Skip " button was taken off from this screen, since skipping this screen doesn't make sense. Fixed.
