### ISSUE TITLE
Cannot proceed post selecting Lead as a Preference and choosing the fields

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#130]
Describe bug with steps:

1. Create an organisation and integrate with SF
2. Select lead as a preference
3. select the field values and click on SUBMIT. 
4. Current behavior: You will see the error, the user sees a blank screen on the extension side.
https://www.loom.com/share/74add6adb77e4b53b8456abf5b6636b3

![image](https://user-images.githubusercontent.com/55691499/75958142-a3624380-5ee1-11ea-9552-525d1301abc9.png)

**Expected behavior:**

User should land on admin homescreen upon selection of preference fields.

**Comment by sharangsamonkar** [comment]
@ralph-ajency looks fixed. please check and update.

**Comment by HazelColaco19** [comment]
Fixed
