### ISSUE TITLE
On click of chats in Salesforce: Missing link and whatsapp user name

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#140]
**Describe the Bug**

1. Missing the conversation URL from the top heading denoted with the arrow.
2. Also missing the name the whatsapp user. As it can be seen on screenshot, it just shows the number instead of fetching the name of the employee/ whatsapp user

![image](https://user-images.githubusercontent.com/55691499/76214470-d0408e80-6232-11ea-9c44-b167f1e20bb7.png)

**Expected:**
SF should be configured to display
a. the URL
b. The saved name of the whatsapp user

**Comment by ralph-ajency** [comment]
@HazelColaco19 - Conversation Link showed in SF view for account (ralph-aj@ajency.in)

**Note:** view changed for conversation link can be done in compact layout on respective Object.

**Comment by HazelColaco19** [comment]
Fixed
