### ISSUE TITLE
Rearrange the fields to have the owner field place as shown in the design

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#142]
**Describe the bug with steps:**

1. The undefined tag should not appear for group chats
2. The owner field should appear at the bottom as shown in the design

![image](https://user-images.githubusercontent.com/55691499/76215898-a9d02280-6235-11ea-9c72-b655d032cac7.png)

**Comment by ralph-ajency** [comment]
**Note:** View changes can be modified in page layout in SF Object.

@HazelColaco19 - Re-arranged the filed in SF view for account (ralph-aj@ajency.in)

**Comment by HazelColaco19** [comment]
Fixed
