### ISSUE TITLE
Current sync conversation breaks when starred message of a single conversation is synced 

### ISSUE THREAD

**Issue by AkshataSail** [ajency/Sync-WhatsApp-Conversation#25]
Go to a conversation
conversation info -starred message
start "current sync conversation"
Error: sync breaks

![Screenshot 2019-12-12 at 1 09 44 PM](https://user-images.githubusercontent.com/47238092/70692129-b13c6a00-1ce0-11ea-9bdc-c8f79987a8e3.png)

**Comment by TejalBandekar** [comment]
Fixed.
