### ISSUE TITLE
Verification emails are sent out with a delay of more than 4 minutes

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#40]
**Describe the bug**

On click of " Create Account " on Create Organisation screen the verification email sent to the admin is sent out with a delay of about 4 minutes. This leads the user to assume that he is stuck or nothing has happened.

**Expected Result**

The emails should be sent out with minimum delay as possible - maybe less than a minute or two.

**Comment by 27amaldev09** [comment]
The email sending depends on the email transport

**Comment by HazelColaco19** [comment]
Okay
