### ISSUE TITLE
On clicking the extension on other tabs , no 'sync contact' button is visible 

### ISSUE THREAD

**Issue by AkshataSail** [ajency/Sync-WhatsApp-Conversation#5]
>Go to chrome://extensions/
>Click open the extension favicon 
Error: No 'sync contacts' button is visible on click

![Screenshot 2019-12-03 at 11 45 54 AM](https://user-images.githubusercontent.com/47238092/70025260-7e98c000-15c2-11ea-9f17-bb39f58ae122.png)

**Comment by 27amaldev09** [comment]
The UI has been changed  for this

**Comment by AkshataSail** [comment]
fixed.
