### ISSUE TITLE
post creation of organisation and adding phone number : The added phone number could not login. Goes in loop, see screenshot

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#60]
![image](https://user-images.githubusercontent.com/55691499/73135343-f6391780-4066-11ea-8480-a0a01033aa58.png)

On refresh of the screen above, you get the screen below. On click of any buttons on this screen, there is no response

![image](https://user-images.githubusercontent.com/55691499/73135372-487a3880-4067-11ea-8552-efc50a37a75f.png)

**Comment by 27amaldev09** [comment]
The issue might be because of no proper internet, because the extension only has access to the website DOM

**Comment by HazelColaco19** [comment]
Works now. Was a connectivity issue
