### ISSUE TITLE
Quick Response template > No template present : Show a message instead of showing empty banner

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#90]
Expected Message: " Click on Edit to add response templates "

![image](https://user-images.githubusercontent.com/55691499/74006794-ca8d2a00-49a2-11ea-92a2-1aabf096e42f.png)

**Comment by 27amaldev09** [comment]
The issue is fixed with having a ADD button when there are no quick responses

**Comment by HazelColaco19** [comment]
fixed
