### ISSUE TITLE
QRT> Add New > Create response > redirects to response listing pop up but shows blank pop up

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#96]
Expected: The user should see the created template

Response created 

![image](https://user-images.githubusercontent.com/55691499/74010662-05479000-49ac-11ea-9488-bb611d32570e.png)

Blank pop up

![image](https://user-images.githubusercontent.com/55691499/74010677-0d9fcb00-49ac-11ea-887e-59d462b7e06d.png)

**Comment by 27amaldev09** [comment]
Indexed db was not initialized and the issue cant be replicated

**Comment by HazelColaco19** [comment]
Fixed
