### ISSUE TITLE
QRT > Add new > Create response > Close > Add + in input area of whatsapp : The added template does  not display

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/Sync-WhatsApp-Conversation#97]
![image](https://user-images.githubusercontent.com/55691499/74011090-f3b2b800-49ac-11ea-9bae-b3e750f5ea73.png)

**Comment by 27amaldev09** [comment]
Indexed db was not initialized and the issue cant be replicated

**Comment by HazelColaco19** [comment]
Fixed
